### ISSUE TITLE
更换生产环境代理地址，登录成功后无法跳转

### ISSUE THREAD

**Issue by feixuezhang** [dgiot/dgiot-dashboard#330]
### 描述问题
更换生产环境代理地址，登录成功后无法跳转，刷新之后跳转总控无法加载在本地运行也是出现这个错误
报错
![image](https://user-images.githubusercontent.com/57926891/143727306-3e9070df-00e4-4d16-80b0-35e09a7f82f6.png)
骑着乌龟赛跑(zhangxiaoke2008@qq.com)  10:35:48

骑着乌龟赛跑(zhangxiaoke2008@qq.com)  10:36:07
build.umd.js?c018:3024 
        
       Error: Cannot find module './views/equipment_management/platform_overview'

服务器Nginx 配置是这样的

![0L%)AH6$0T$EBF38WE(D)`F](https://user-images.githubusercontent.com/57926891/143727260-8b9af23f-cce4-4b54-8e8f-0745a5a5f639.png)

本地前端生产环境配置
![%D9VE 5_L34YNVARVCTN4JD](https://user-images.githubusercontent.com/57926891/143727280-0e6dc3ac-6e02-4312-8f6e-28bde8cc0d2a.png)
![6LR7LYHLEQ97BNB5DAOKUA3](https://user-images.githubusercontent.com/57926891/143727284-9b58a0ee-6590-4412-8266-fc5da8de5b28.png)

**Comment by h7ml** [comment]
- 修改生成环境代理地址。请修改[developer.config.js](https://github.com/dgiot/dgiot-dashboard/blob/master/src/config/developer.config.js#L4) 文件夹。
- 代理地址末尾不需要``/``

**Comment by h7ml** [comment]
``Error: Cannot find module './views/equipment_management/platform_overview'`` 该问题是因为后端数据库菜单路由与[dgiot-dashboard](https://github.com/dgiot/dgiot-dashboard/)   [路由页面](https://github.com/dgiot/dgiot-dashboard/tree/master/src/views)参数不一致。建议拉取最新[dgiot](https://github.com/dgiot/dgiot)
